name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    strategy:
      matrix:
        go: [ '1.18','1.19','1.20','1.21' ]
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic -timeout=10m

      - name: Codecov
        uses: codecov/codecov-action@v3
        if: matrix.os == 'ubuntu-latest'